_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.1
            "8":
                - 1
                - 5
            "12": 0.18.1
            "13": darwin-x86_64
architecture:
    value: UNET
dataset:
    value: ASCAT-A
epochs:
    value: 1000
learning_rate:
    value: 0.001
